version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            apt-get install --no-install-recommends -y qemubuilder debootstrap
      # Reuse cached packages and build image
      - restore_cache:
          key: cache-0001
      - run:
          command: |
            sudo debootstrap --arch mipsel --foreign --include=apt --cache-dir=/var/cache/pbuilder/aptcache/ --keyring=/etc/apt/trusted.gpg --force-check-gpg sid /var/cache/pbuilder/build/25855a http://ftp.uk.debian.org/debian/
      - save_cache:
          key: cache-0001
          paths:
            - ~/var/cache/pbuilder/aptcache/
            - ~/var/cache/pbuilder/build
      - run:
          command: |
            echo hi
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
