version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # Reuse cached packages and build image
      - restore_cache:
          key: cache-0001
      - run:
          command: |
            echo hi
      - save_cache:
          key: cache-0001
          paths:
            - ~/.cache
      - run:
          command: |
            echo hi
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
